### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by teneightfive** [UKHomeOffice/passports-form-controller#33]
Valid phone number formats are being returned as invalid if they contain spaces. 

I'm using the [phonenumber](https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/validation/validators.js#L52-L54) validator and when a user enters `020 7946 0937` or `07700 900579` (example numbers used on the hackpad) it returns invalid. 

I also noticed that the tests for ukmobilephone treat numbers with spaces as [invalid](https://github.com/UKHomeOffice/passports-form-controller/blob/master/test/spec/spec.validators.js#L269). Is there a reason for this?

If not, I will add a PR to trim whitespace before running the regex.

**Comment by edwardhorsford** [comment]
IMHO we should be very allowing - and strip characters we don't need. So strip ` `, `/`, `-`, etc.

FYI [this](https://www.refheap.com/269350ccb86bb0c09dcfaef5b) list of formats came up on slack the other week.

**Comment by teneightfive** [comment]
Running that list of numbers against the current validator returns this (numbers indicate a fail and show count):

```
        ✓ string 07700900456
        ✓ string +447700900456
        1) string (+44) 07700900456
        2) string 07700 900 456
        3) string 07700 900456
        4) string +447700 900456
        ✓ string 01144960573
        ✓ string +441144960573
        5) string +44114 4960573
        6) string 0114 4960573
        7) string 0114 496 0573
        8) string (0114) 496 0573
        9) string (0114) 4960573
        ✓ string 02079460000
        ✓ string +442079460000
        10) string 020 79460000
        11) string 020 7946 0000
        ✓ string 01632960123
        ✓ string +441632960123
        12) string +441632 960123
        13) string 01632 960123
        14) string 01632 960 123
        15) string (01632) 960123
        16) string (01632) 960 123
        ✓ string 0169772551
        ✓ string +44169772551
        17) string 0169 772551
        18) string 0169 772 551
        19) string (0169) 772551
        20) string (0169) 772 551
```

**Comment by teneightfive** [comment]
Wonder whether this should be used as part of the test case?

**Comment by gavboulton** [comment]
On passports we're applying formatters to phone number fields in the fields config. You'll want to start with `removespaces` (https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/formatting/formatters.js#L21).

Validating a phone number, accounting for brackets and dashes etc. could get quite complicated. Applying formatters simplifies this

**Comment by teneightfive** [comment]
@gavboulton ah, I see. I just tried this by adding a formatter to the field I'm validating. It does now pass the validation with spaces in the value but it actually changes the format before replaying on the page. So if they error on another field on that page it sends the formatted value but to the form and when replaying later on, like on a check your answers page, it displays the formatted value rather than the value they entered. 

This goes against [the guidance](https://designpatterns.hackpad.com/Phone-numbers-9Gnnfam9Aqr#:h=Play-back-phone-numbers-in-the) currently on the hackpad.

Is there a way to apply the formatter only to validate the input?

**Comment by gavboulton** [comment]
The formatters need to be applied before validation. I agree that it's a problem that the user input is changed. Later on, when replaying the value to the user, you have control as to how this value is displayed in the view.

The main problem we've seem with user input being changed is with dates. We currently have a custom controller that preserves the input values until all validation has passed. It seems like this type functionality needs adding in this module.

**Comment by teneightfive** [comment]
@gavboulton do you have a link to this controller somewhere? Curious to see if something similar could be used on our app.

**Comment by gavboulton** [comment]
It's behind closed doors at the moment but we do have a plan to open it soon.

**Comment by gavboulton** [comment]
@teneightfive Are you happy for me to close this now?
