### ISSUE TITLE
The date component validators are too strict

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/passports-form-controller#39]
It seems to me that the validators for date components, i.e. "date-year", "date-month" and "date-day", are too strict. For example, consider a user who is filling out the input-date mixin with the date "7th February, 1998". With the current validators we would require them to enter "07" as the day and "02" as the month, when we are perfectly capable of parsing the shorter "7" for the day and "2" as the month.

(Technically the same issue exists for the year but how often are users inputting years prior to 1000 AD? I would accept that for the year it might make more sense to keep the stricter validation but am curious to here what others think.)

We currently have an expectation in some HOF-based forms that this shorthand input should be accepted. So it would be nice if we could standardise with the rest to the HMPO stack if at all possible.

Would a PR for this issue be welcome or are there problems in making such a change? Should we make the year field accept '42' as '0042' (i.e. 42 AD)?

**Comment by gavboulton** [comment]
I agree that they're strict but it's so that we can reliably validate the date as a whole to give the user an accurate validation message.

We too accept single digit numbers for day and month (and prepend zeroes) and two digits for year (and insert the correct century). We make these changes in our controller but are careful to preserve the user's input data when there is an error.

**Comment by daniel-ac-martin** [comment]
I think you should still be able to validate the date as a whole even with a less strict validation on the components. You just need to prepend a zero to a single digit month or year, which is what I do in the new date controller.

I don't understand how you can reliably insert the correct century. That's basically the millennium bug all over again! ;-)

Do you just assume the date is in the past and set 19 as the century unless the year is <= 16? (That would be kind of neat except that you need to know whether the date should be in the future or the past. - I suppose we could inspect the validators, but that won't always work.)

**Comment by gavboulton** [comment]
We're only dealing with two sorts of dates at the moment with different criteria; the user needs to be a certain age or over to apply and passports will expire within a certain window. Our implementation wouldn't be suitable to cover all scenarios.

It seems that the day and month are okay then but we should relax the year validator.

**Comment by daniel-ac-martin** [comment]
I don't understand how you can be accepting single digits for the month and day if you are using the current validators. As they use the following regex:

```js
 /^\d{2}$/
```

Which should only match on double digits.

I'd like to change them to be:

```js
 /^\d{1,2}$/
```

Are you sure you're using those validators?

**Comment by gavboulton** [comment]
We're using the `_process` (but should probably be using `process`) method to format the values.

**Comment by gavboulton** [comment]
It looks like it's being done in passports-date-controller too.

**Comment by HughePaul** [comment]
date logic has been moved to the hmpo-components module
