### ISSUE TITLE
One of my templates uses a partial which needs some data sent into it.

### ISSUE THREAD

**Issue by sebinsua** [UKHomeOffice/passports-form-controller#4]
I am going to create the ability to set some templateDefaults against the options used to create a FormController.

**Comment by lennym** [comment]
I would recommend using the `locals` hook on the form controller to do this - https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/form.js#L87-L89

eg.

```javascript
MyController.prototype.locals = function (req, res) {
  return { stepNumber: 2 };
};
```
