### ISSUE TITLE
Certain validators implicitly make a field required.

### ISSUE THREAD

**Issue by sebinsua** [UKHomeOffice/passports-form-controller#5]
Certain validators implicitly make a field required.

For example, while it is possible to mark a field as required with the 'required' validator, if you use any validator that is implemented with a regex that matches with a `+` this ensures that one-or-more characters must match and therefore, even if was not marked as a required field it is de facto a required field.

As a concrete example, see [numeric](https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/validation/validators.js#L44).

Shouldn't we be able to define fields that are numeric but also optional? When a field is not marked as required - as it is considered optional - shouldn't it also validate successfully for an empty field?

For now, I used a regex with a * instead of a +, but perhaps we should implement this in a shared way differently.

@gavboulton @lennym

**Comment by lennym** [comment]
This makes perfect sense. I'd happily merge a `s/+/*` PR.

**Comment by sebinsua** [comment]
The more I think about this the stranger it feels.

The example I was thinking of was a 'passport number' field.

In LSR this field is optional (since often they have no record of the number of the passport that has been lost). Therefore the validation should be (1) if it contains something that something should be a number, (2) it should not fail if it's an empty string, (2) if it contains a string then that should be 9 characters long.

Should all the validators return true for empty strings?

I didn't feel so weird about 'numeric' being `Validators.regex(value, /^\d*$/)` but I feel a lot weirder about something called 'exactlength' being `Validators.string(value) && (value.length === length || value.length === 0)`.

I think I'm going to just make custom validators for now as whatever exists should be semantic and consistent.

**Comment by lennym** [comment]
I'm actually quite happy with the idea of all validators accepting an empty value (except `required` obviously).
