### ISSUE TITLE
Field value cleared if dependent check passed

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/passports-form-controller#62]
If a dependent field check passes, validation for the field is skipped. However, on [this line](https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/validation/index.js#L89) the value for the field is cleared.  Is this desired behaviour?  

We are using this feature in a few applications with the same use case - a field is only required depending on a certain condition, if the condition is met then the field is optional, however this now appears to not be working in the way we originally thought!

Is there a use case where we would desire the field to be cleared if the condition is met? Or are we able to remove this line?

**Comment by gavboulton** [comment]
I don't think anything has changed. If a field value isn't needed (due to the dependent field condition not being met) then its value is, in most cases, set to an empty string.

**Comment by joefitter** [comment]
Nothing has changed, I meant it looks like we have misunderstood the functionality, but I believe our interpretation could be more useful than the current implementation.

If what you describe above is the desired behaviour, then in order to be consistent with the rest of the form, wouldn't it be better to simply delete the key from req.form.vaues, so as not to add the field to the session model?

Regardless of this though, our use case is 2 checkboxes, one of the, must be checked, but it doesn't matter which one. So in other words both checkboxes are `required` and both have dependent set to each other, so if checkbox 1 is checked, checkbox 2 is no longer required, and vise versa, but it is still optional - select one or more values.

**Comment by joefitter** [comment]
This particular case would actually solved with the addition of a checkbox group as it would act like one field

**Comment by gavboulton** [comment]
It sounds like a new feature to me.

**Comment by joefitter** [comment]
perhaps not, I think I have talked myself out of it! checkbox-group will solve this particular issue, however, to be consistent with other blank fields I do think we should `delete` the key rather than setting it to an empty value

**Comment by gavboulton** [comment]
After an initial look at the tests, it will set fields with the `boolean-strict` formatter (so checkboxes) to false. I can see this being useful.

**Comment by joefitter** [comment]
I obviously didn't dig deep enough - yes that sounds useful and I wasn't aware of the `boolean-strict` formatter, so thanks!

**Comment by joefitter** [comment]
looking at this in more detail - I'm not sure that this is a useful feature - if you submit a form without checking a checkbox it wont be included in the sessionModel, however if you submit a form with a negated checkbox through using dependent, it will be included in the sessionModel (still as an empty string from testing in an application). This will likely cause problems when looping over sessionModel fields for creating a confirm page and structuring an email
